
-- V26 MODO BETA CON PRECIOS Y EXPIRACION
ALTER TABLE users ADD COLUMN IF NOT EXISTS plan TEXT DEFAULT 'pro';
ALTER TABLE users ADD COLUMN IF NOT EXISTS plan_days INT DEFAULT 30;
ALTER TABLE users ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE users ADD COLUMN IF NOT EXISTS videos_used INT DEFAULT 0;

-- Politica
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all" ON users;
CREATE POLICY "Allow all" ON users FOR ALL USING (true) WITH CHECK (true);

SELECT username, plan, expires_at, is_active,
  CASE WHEN expires_at < NOW() THEN 'EXPIRADO' ELSE CONCAT(CEIL(EXTRACT(EPOCH FROM (expires_at - NOW()))/86400)::INT, ' días') END as restante
FROM users;
